image:
  repository: 192.168.122.1:5000/my-python-app
  tag: latest

service:
  type: ClusterIP
  port: 5000

resources:
  requests:
    cpu: "50m"
    memory: "128Mi"
  limits:
    cpu: "100m"
    memory: "256Mi"

serviceMonitor:
  enabled: true
  path: /metrics
  interval: 15s
