apiVersion: v1
kind: Service
metadata:
  name: my-python-app
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5000
      protocol: TCP
      name: http
  selector:
    app: my-python-app
